---
- name: Install Nginx
  apt:
    name: nginx
- name: Run Nginx
  service:
    name: nginx
    state: started
    enabled: true
- name: Copy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
